# Generated by Django 2.2.6 on 2020-02-24 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('tel', models.PositiveIntegerField()),
                ('password', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('designation', models.CharField(max_length=40)),
                ('unite', models.CharField(max_length=40)),
                ('credit', models.PositiveIntegerField()),
                ('coeff', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('semestre', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-niveau'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nv', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloc', models.CharField(max_length=30)),
                ('design', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('enseignants', models.ManyToManyField(to='dashboard.Enseignant')),
                ('opr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(blank=True, max_length=10, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='dashboard.Enseignant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='dashboard.Module')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='dashboard.Salle')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Niveau'),
        ),
        migrations.AddField(
            model_name='module',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Enseignant'),
        ),
        migrations.CreateModel(
            name='EmploiTemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestree', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('fifth_first', models.ManyToManyField(blank=True, related_name='perides_seventeen', to='dashboard.Periode')),
                ('fifth_forth', models.ManyToManyField(blank=True, related_name='perides_twenty', to='dashboard.Periode')),
                ('fifth_second', models.ManyToManyField(blank=True, related_name='perides_eighteen', to='dashboard.Periode')),
                ('fifth_third', models.ManyToManyField(blank=True, related_name='perides_nineteen', to='dashboard.Periode')),
                ('first_first', models.ManyToManyField(blank=True, related_name='peride_one', to='dashboard.Periode')),
                ('first_forth', models.ManyToManyField(blank=True, related_name='perides_four', to='dashboard.Periode')),
                ('first_second', models.ManyToManyField(blank=True, related_name='perides_two', to='dashboard.Periode')),
                ('first_third', models.ManyToManyField(blank=True, related_name='perides_three', to='dashboard.Periode')),
                ('forth_first', models.ManyToManyField(blank=True, related_name='perides_thirteen', to='dashboard.Periode')),
                ('forth_forth', models.ManyToManyField(blank=True, related_name='perides_sixteen', to='dashboard.Periode')),
                ('forth_second', models.ManyToManyField(blank=True, related_name='perides_fourteen', to='dashboard.Periode')),
                ('forth_third', models.ManyToManyField(blank=True, related_name='perides_fifteen', to='dashboard.Periode')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Niveau')),
                ('second_first', models.ManyToManyField(blank=True, related_name='peride_five', to='dashboard.Periode')),
                ('second_forth', models.ManyToManyField(blank=True, related_name='perides_eight', to='dashboard.Periode')),
                ('second_second', models.ManyToManyField(blank=True, related_name='perides_six', to='dashboard.Periode')),
                ('second_third', models.ManyToManyField(blank=True, related_name='perides_seven', to='dashboard.Periode')),
                ('third_first', models.ManyToManyField(blank=True, related_name='perides_nine', to='dashboard.Periode')),
                ('third_forth', models.ManyToManyField(blank=True, related_name='perides_twelve', to='dashboard.Periode')),
                ('third_second', models.ManyToManyField(blank=True, related_name='perides_ten', to='dashboard.Periode')),
                ('third_third', models.ManyToManyField(blank=True, related_name='perides_eleven', to='dashboard.Periode')),
            ],
        ),
    ]
