# Generated by Django 2.2.6 on 2020-09-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200926_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='enseignants',
        ),
    ]
