# Generated by Django 2.2.6 on 2020-03-04 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200304_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploitemps',
            name='apdated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emploitemps',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
