# Generated by Django 2.2.6 on 2020-03-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200304_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('cours', models.PositiveSmallIntegerField()),
                ('td', models.PositiveSmallIntegerField()),
                ('tp', models.PositiveSmallIntegerField()),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Module')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Niveau')),
            ],
        ),
        migrations.DeleteModel(
            name='Canvas',
        ),
    ]
