# Generated by Django 2.2.6 on 2020-09-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_salle_enseignants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prof',
        ),
    ]
