# Generated by Django 2.2.6 on 2020-04-13 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200307_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivaux', to='dashboard.Niveau'),
        ),
        migrations.AlterField(
            model_name='module',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profs', to='dashboard.Enseignant'),
        ),
    ]
