# Generated by Django 2.2.6 on 2020-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_module_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploitemps',
            name='group_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
