# Generated by Django 2.2.6 on 2020-09-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_emploitemps_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='salles',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Salle'),
        ),
    ]
