# Generated by Django 2.2.6 on 2020-04-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200414_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvastimetable',
            name='modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas', to='dashboard.Module'),
        ),
    ]
