# Generated by Django 2.2.6 on 2020-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200929_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='science1_J1',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science1_J2',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science1_J3',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science1_J4',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science1_J5',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science2_J1',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science2_J2',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science2_J3',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science2_J4',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science2_J5',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science3_J1',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science3_J2',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science3_J3',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science3_J4',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science3_J5',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science4_J1',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science4_J2',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science4_J3',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science4_J4',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science4_J5',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science5_J1',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science5_J2',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science5_J3',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science5_J4',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='science5_J5',
        ),
    ]
