# Generated by Django 2.2.6 on 2020-10-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_enseignant_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='departement',
            field=models.CharField(choices=[('1', 'informatique'), ('2', 'mathématique'), ('3', 'autre')], max_length=30),
        ),
    ]
