# Generated by Django 2.2.6 on 2020-04-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_canvastimetable_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvastimetable',
            name='slug',
            field=models.SlugField(),
        ),
    ]
