# Generated by Django 2.2.6 on 2020-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200609_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='tel',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
