# Generated by Django 2.2.6 on 2020-10-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20201016_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.DeleteModel(
            name='ChargeHoraire',
        ),
        migrations.DeleteModel(
            name='Science',
        ),
    ]
