# Generated by Django 2.2.6 on 2020-06-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200609_1444'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='canvastimetable',
            table='canvasTimeTable',
        ),
        migrations.AlterModelTable(
            name='emploitemps',
            table='emploiTemps',
        ),
        migrations.AlterModelTable(
            name='module',
            table='module',
        ),
        migrations.AlterModelTable(
            name='salle',
            table='salle',
        ),
    ]
