# Generated by Django 2.2.6 on 2020-06-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200609_1503'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enseignant',
            table='Enseignant',
        ),
    ]
