# Generated by Django 2.2.6 on 2020-06-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200609_1508'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='niveau',
            table='Niveau',
        ),
    ]
