# Generated by Django 2.2.6 on 2020-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200609_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='groupe_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
