# Generated by Django 2.2.6 on 2020-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200609_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='type_of',
            field=models.CharField(choices=[('1', 'TP'), ('2', 'TD'), ('3', 'Amphi')], max_length=10),
        ),
    ]
