# Generated by Django 2.2.6 on 2020-09-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_staff_staffpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffPermission',
        ),
    ]
