# Generated by Django 2.2.6 on 2020-09-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200912_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
