# Generated by Django 2.2.6 on 2020-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Materil_pic'),
        ),
    ]
