# Generated by Django 2.2.6 on 2020-09-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_material_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeHoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3'), ('4', 'S4'), ('5', 'S5'), ('6', 'S6'), ('7', 'M1'), ('8', 'M2')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('1', 'TP'), ('2', 'TD'), ('3', 'Amphi')], max_length=20)),
                ('groupe', models.CharField(max_length=3)),
                ('occupe', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='opr',
        ),
        migrations.AddField(
            model_name='material',
            name='salles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Salle'),
        ),
        migrations.AddField(
            model_name='module',
            name='cours',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='td',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='tp',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='retering_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='unite',
            field=models.CharField(choices=[('1', 'Fondamentale'), ('2', 'Methodologie')], max_length=40),
        ),
        migrations.RemoveField(
            model_name='salle',
            name='enseignants',
        ),
        migrations.AddField(
            model_name='salle',
            name='enseignants',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Enseignant'),
        ),
        migrations.DeleteModel(
            name='CanvasTimeTable',
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Enseignant'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Niveau'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science1_J1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J1', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science1_J2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J2', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science1_J3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J3', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science1_J4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J4', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science1_J5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J5', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science2_J1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J1', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science2_J2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J2', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science2_J3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J3', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science2_J4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J4', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science2_J5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J5', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science3_J1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J1', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science3_J2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J2', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science3_J3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J3', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science3_J4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J4', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science3_J5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J5', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science4_J1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J1', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science4_J2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J2', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science4_J3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J3', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science4_J4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J4', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science4_J5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J5', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science5_J1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J1', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science5_J2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J2', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science5_J3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J3', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science5_J4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J4', to='dashboard.Science'),
        ),
        migrations.AddField(
            model_name='chargehoraire',
            name='science5_J5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J5', to='dashboard.Science'),
        ),
    ]
