# Generated by Django 2.2.6 on 2020-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200917_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='cours',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='td',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='tp',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
