# Generated by Django 2.2.6 on 2020-09-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200917_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='enseignants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Enseignant'),
        ),
    ]
