# Generated by Django 2.2.6 on 2020-09-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200917_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='bloc',
            field=models.CharField(choices=[('1', 'Bloc 30Salles'), ('2', 'Bloc 22Salles')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salle',
            name='design',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='groupe',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
