# Generated by Django 2.2.6 on 2020-09-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20200917_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='design',
            field=models.CharField(max_length=20),
        ),
    ]
