# Generated by Django 2.2.6 on 2020-09-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20200917_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargehoraire',
            name='enseignant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Enseignant'),
        ),
    ]
