# Generated by Django 2.2.6 on 2020-09-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20200918_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargehoraire',
            name='science1_J1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J1', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science1_J2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J2', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science1_J3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J3', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science1_J4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J4', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science1_J5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science1_J5', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science2_J1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J1', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science2_J2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J2', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science2_J3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J3', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science2_J4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J4', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science2_J5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science2_J5', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science3_J1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J1', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science3_J2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J2', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science3_J3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J3', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science3_J4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J4', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science3_J5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science3_J5', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science4_J1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J1', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science4_J2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J2', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science4_J3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J3', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science4_J4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J4', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science4_J5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science4_J5', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science5_J1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J1', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science5_J2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J2', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science5_J3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J3', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science5_J4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J4', to='dashboard.Science'),
        ),
        migrations.AlterField(
            model_name='chargehoraire',
            name='science5_J5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='science5_J5', to='dashboard.Science'),
        ),
    ]
