# Generated by Django 2.2.6 on 2020-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20200919_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='type_of',
            field=models.CharField(choices=[('TP', 'TP'), ('TD', 'TD'), ('Amphi', 'Amphi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='science',
            name='nature',
            field=models.CharField(choices=[('TP', 'TP'), ('TD', 'TD'), ('Amphi', 'Amphi')], max_length=20),
        ),
    ]
