# Generated by Django 2.2.6 on 2020-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='user.StaffPermission'),
        ),
    ]
